# 100 exercises of numpy

### 1.Import numpy package as np

In [1]:
import numpy as np

### 2. Print the numpy version and configuration

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/ml_and_dl/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/ml_and_dl/env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/ml_and_dl/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/ml_and_dl/env

### 3. Create a null vector of size 10

In [3]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value is 1.

In [4]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49

In [5]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector

In [6]:
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 7.Create a 3X3 matrix with values ranging from 0 to 8 

In [7]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find a indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### 9. Create a 3X3 identity matrix

In [9]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3X3X3 array with random values

In [10]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.95335223 0.63054763 0.68639657]
  [0.40778569 0.11813635 0.96318998]
  [0.49728531 0.08509153 0.43912722]]

 [[0.02549524 0.85167988 0.57600194]
  [0.57707654 0.40057594 0.9121599 ]
  [0.25960375 0.57829489 0.63588393]]

 [[0.78118473 0.87755901 0.58793456]
  [0.12804251 0.46549419 0.9270441 ]
  [0.29885664 0.12955326 0.75347787]]]


### 11. Create a 10X10 array with random values and find the minimum and maximum values

In [11]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Z)
print(Zmin)
print(Zmax)

[[0.54420914 0.00455544 0.92314342 0.6627801  0.50179537 0.15761747
  0.22222615 0.47254105 0.49980873 0.53652349]
 [0.7863689  0.18737924 0.13976368 0.66231899 0.32715769 0.17644831
  0.15744875 0.86605544 0.94572834 0.79288198]
 [0.15841394 0.69586762 0.46220822 0.32986184 0.59639625 0.62487651
  0.65258634 0.14720503 0.53490048 0.57995908]
 [0.69132727 0.05410684 0.95593782 0.38781153 0.07398014 0.66000583
  0.77371885 0.0731142  0.70513117 0.86945815]
 [0.57190866 0.36411757 0.66268711 0.06085655 0.84051744 0.97188734
  0.27917966 0.52182286 0.47831167 0.21430078]
 [0.71791306 0.68042058 0.55048918 0.39636619 0.33582296 0.3108178
  0.54709618 0.17850585 0.12100805 0.77193365]
 [0.39095414 0.55573858 0.45791202 0.40151811 0.11485193 0.26908728
  0.87509252 0.06616135 0.76645598 0.17630701]
 [0.0441625  0.7523384  0.85289508 0.03270328 0.24618228 0.33177992
  0.49390409 0.41087721 0.30556229 0.85530751]
 [0.4551298  0.08562149 0.16421252 0.72323855 0.71966795 0.50861505
  0.01441045 

### 12. Create a random vector of size 30 and find the mean value

In [12]:
Z=np.random.random((30))
m=Z.mean()
print(m)

0.4543057479552966


### 13. Create a 2d array with 1 on the border and 0 inside

In [13]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14.What is the result of the following expression?

In [14]:
0 * np.nan


nan

In [15]:
np.nan == np.nan


False

In [16]:
np.inf > np.nan


False

In [17]:
np.nan - np.nan


nan

In [18]:
0.3 == 3 * 0.1

False

### 15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 16. Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 17. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


### 18. Create a checkerboard 8x8 matrix using the tile function

In [22]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 19, Normalize a 5x5 random matrix

In [23]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.66266239 0.35311071 0.2118127  0.84407915 0.99347976]
 [0.46743619 0.57485917 0.30169362 0.29724335 0.95322547]
 [0.58800016 0.1864193  0.         0.69600999 0.03517962]
 [0.37856299 0.47304799 0.78234125 0.6225578  0.36167475]
 [0.43767243 0.58489828 0.05692    0.041833   1.        ]]


### 20. Create a custom dtype that describes a color as four unisgned bytes (RGBA) 

In [24]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

<ipython-input-24-349c455c09b5>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


### 21.  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 22. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### 23.  What is the output of the following script?

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


### 24. Consider an integer vector Z, which of these expressions are legal?

In [28]:

2 << Z >> 2


array([  0,   1,   2,   4,   0,   0,   0,   0,   0, 256, 512], dtype=int32)

In [29]:
Z <(- Z)


array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [30]:
Z**Z


ValueError: Integers to negative integer powers are not allowed.

In [31]:
1j*Z


array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [32]:
Z/1/1


array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [33]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 25.  What are the result of the following expressions?

In [34]:
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)

<ipython-input-34-6a54f48d784e>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-34-6a54f48d784e>:2: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)
<ipython-input-34-6a54f48d784e>:3: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-34-6a54f48d784e>:4: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0.)


nan

### 26. How to round away from zero a float array ? 

In [35]:
Z = np.random.uniform(-10,+10,10)
print (np.trunc(Z + np.copysign(0.5, Z)))

[ 6.  5.  3. -5.  8. -2. -1.  3. -4.  2.]


### 27.  Extract the integer part of a random array using 5 different methods

In [36]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 5. 4. 8. 8. 5. 6. 0. 1. 8.]
[9. 5. 4. 8. 8. 5. 6. 0. 1. 8.]
[9. 5. 4. 8. 8. 5. 6. 0. 1. 8.]
[9 5 4 8 8 5 6 0 1 8]
[9. 5. 4. 8. 8. 5. 6. 0. 1. 8.]


### 28. . Create a 5x5 matrix with row values ranging from 0 to 4

In [37]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 29. Consider a generator function that generates 10 integers and use it to build an array

In [38]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 30. . Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [39]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 31.Create a random vector of size 10 and sort it 

In [40]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.02693749 0.10713057 0.23292644 0.43861614 0.45471921 0.47289653
 0.55697288 0.61256361 0.77647808 0.98298852]


### 32.  How to sum a small array faster than np.sum?

In [41]:
Z = np.arange(10)
np.add.reduce(Z)


45

### 33. Consider two random array A anb B, check if they are equal

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


### 34. Make an array immutable (read­only)

In [43]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

### 35.  Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [44]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.13259549 0.36716682 0.56430848 0.79518037 0.89359337 1.05782412
 0.52791766 0.82992526 0.5979483  0.55809451]
[1.56149902e+00 9.04072728e-01 9.34455263e-01 1.33849774e+00
 1.32163089e+00 7.18415818e-01 6.45394882e-05 8.63929990e-01
 6.55134823e-01 2.87513960e-01]


### 36. Create random vector of size 10 and replace the maximum value by 0

In [48]:
Z = np.random.random(10)
X=Z[Z.argmax()]
X=0
print(X)


0


### 37. Create a structured array with xand ycoordinates covering the [0,1]x[0,1] area


In [49]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

### 38.  Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi ­ yj))

In [50]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.1636371179666


### 39. Print the minimum and maximum representable value for each numpy scalar type

In [52]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 40. How to print all the values of an array?

In [53]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)


ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation